# http://www.neuromorphometrics.com/?page_id=23#academic

atlas = {
0:"Background and skull",
1:"Non-ventricular CSF",
5:"3rd Ventricle",
12:"4th Ventricle",
16:"5th Ventricle",
24:"Right Accumbens Area",
31:"Left Accumbens Area",
32:"Right Amygdala",
33:"Left Amygdala",
35:"Pons",
36:"Brain Stem",
37:"Right Caudate",
38:"Left Caudate",
39:"Right Cerebellum Exterior",
40:"Left Cerebellum Exterior",
41:"Right Cerebellum White Matter",
42:"Left Cerebellum White Matter",
43:"Right Cerebral Exterior",
44:"Left Cerebral Exterior",
45:"Right Cerebral White Matter",
46:"Left Cerebral White Matter",
47:"3rd Ventricle (Posterior part)",
48:"Right Hippocampus",
49:"Left Hippocampus",
50:"Right Inf Lat Vent",
51:"Left Inf Lat Vent",
52:"Right Lateral Ventricle",
53:"Left Lateral Ventricle",
54:"Right Lesion",
55:"Left Lesion",
56:"Right Pallidum",
57:"Left Pallidum",
58:"Right Putamen",
59:"Left Putamen",
60:"Right Thalamus Proper",
61:"Left Thalamus Proper",
62:"Right Ventral DC",
63:"Left Ventral DC",
64:"Right vessel",
65:"Left vessel",
70:"Optic Chiasm",
72:"Cerebellar Vermal Lobules I-V",
73:"Cerebellar Vermal Lobules VI-VII",
74:"Cerebellar Vermal Lobules VIII-X",
76:"Left Basal Forebrain",
77:"Right Basal Forebrain",
101:"Right ACgG anterior cingulate gyrus",
102:"Left ACgG anterior cingulate gyrus",
103:"Right AIns anterior insula",
104:"Left AIns anterior insula",
105:"Right AOrG anterior orbital gyrus",
106:"Left AOrG anterior orbital gyrus",
107:"Right AnG angular gyrus",
108:"Left AnG angular gyrus",
109:"Right Calc calcarine cortex",
110:"Left Calc calcarine cortex",
113:"Right CO central operculum",
114:"Left CO central operculum",
115:"Right Cun cuneus",
116:"Left Cun cuneus",
117:"Right Ent entorhinal area",
118:"Left Ent entorhinal area",
119:"Right FO frontal operculum",
120:"Left FO frontal operculum",
121:"Right FRP frontal pole",
122:"Left FRP frontal pole",
123:"Right FuG fusiform gyrus",
124:"Left FuG fusiform gyrus",
125:"Right GRe gyrus rectus",
126:"Left GRe gyrus rectus",
129:"Right IOG inferior occipital gyrus",
130:"Left IOG inferior occipital gyrus",
133:"Right ITG inferior temporal gyrus",
134:"Left ITG inferior temporal gyrus",
135:"Right LiG lingual gyrus",
136:"Left LiG lingual gyrus",
137:"Right LOrG lateral orbital gyrus",
138:"Left LOrG lateral orbital gyrus",
139:"Right MCgG middle cingulate gyrus",
140:"Left MCgG middle cingulate gyrus",
141:"Right MFC medial frontal cortex",
142:"Left MFC medial frontal cortex",
143:"Right MFG middle frontal gyrus",
144:"Left MFG middle frontal gyrus",
145:"Right MOG middle occipital gyrus",
146:"Left MOG middle occipital gyrus",
147:"Right MOrG medial orbital gyrus",
148:"Left MOrG medial orbital gyrus",
149:"Right MPoG postcentral gyrus medial segment",
150:"Left MPoG postcentral gyrus medial segment",
151:"Right MPrG precentral gyrus medial segment",
152:"Left MPrG precentral gyrus medial segment",
153:"Right MSFG superior frontal gyrus medial segment",
154:"Left MSFG superior frontal gyrus medial segment",
155:"Right MTG middle temporal gyrus",
156:"Left MTG middle temporal gyrus",
157:"Right OCP occipital pole",
158:"Left OCP occipital pole",
161:"Right OFuG occipital fusiform gyrus",
162:"Left OFuG occipital fusiform gyrus",
163:"Right OpIFG opercular part of the inferior frontal gyrus",
164:"Left OpIFG opercular part of the inferior frontal gyrus",
165:"Right OrIFG orbital part of the inferior frontal gyrus",
166:"Left OrIFG orbital part of the inferior frontal gyrus",
167:"Right PCgG posterior cingulate gyrus",
168:"Left PCgG posterior cingulate gyrus",
169:"Right PCu precuneus",
170:"Left PCu precuneus",
171:"Right PHG parahippocampal gyrus",
172:"Left PHG parahippocampal gyrus",
173:"Right PIns posterior insula",
174:"Left PIns posterior insula",
175:"Right PO parietal operculum",
176:"Left PO parietal operculum",
177:"Right PoG postcentral gyrus",
178:"Left PoG postcentral gyrus",
179:"Right POrG posterior orbital gyrus",
180:"Left POrG posterior orbital gyrus",
181:"Right PP planum polare",
182:"Left PP planum polare",
183:"Right PrG precentral gyrus",
184:"Left PrG precentral gyrus",
185:"Right PT planum temporale",
186:"Left PT planum temporale",
187:"Right SCA subcallosal area",
188:"Left SCA subcallosal area",
191:"Right SFG superior frontal gyrus",
192:"Left SFG superior frontal gyrus",
193:"Right SMC supplementary motor cortex",
194:"Left SMC supplementary motor cortex",
195:"Right SMG supramarginal gyrus",
196:"Left SMG supramarginal gyrus",
197:"Right SOG superior occipital gyrus",
198:"Left SOG superior occipital gyrus",
199:"Right SPL superior parietal lobule",
200:"Left SPL superior parietal lobule",
201:"Right STG superior temporal gyrus",
202:"Left STG superior temporal gyrus",
203:"Right TMP temporal pole",
204:"Left TMP temporal pole",
205:"Right TrIFG triangular part of the inferior frontal gyrus",
206:"Left TrIFG triangular part of the inferior frontal gyrus",
207:"Right TTG transverse temporal gyrus",
208:"Left TTG transverse temporal gyrus"
}
